### ISSUE TITLE
sgemm outputs large error

### ISSUE THREAD

**Issue by sasao-balmuda** [Idein/qmkl#42]
Hello,

If I modify 'R' value in sgemm example, it outputs serious maximum relarive errors.
2 examples are shown below.  'out1','out2' mean C1,C2 values on the max error.
It seems the issue happens in case 'R' > 4096.
On raspi 3b, default raspbian stretch-lite 2017-08-16.

---------------------
P = 96
Q = 363
R = 15360
ALPHA = 1.000000
BETA = 1.000000
==== sgemm example (ALPHA * 96x363 * 363x15360 + BETA * 96x15360) ====
GPU: 0.080894 [s], 1.32884e+10 [flop/s]
CPU (4 threads): 29.0849 [s], 3.69592e+07 [flop/s]
Minimum absolute error: 0
Maximum absolute error: 726
Minimum relative error: 0
Maximum relative error: 0.666055, out1=364, out2=1090

---------------------
P = 96
Q = 363
R = 4608
ALPHA = 1.000000
BETA = 1.000000
==== sgemm example (ALPHA * 96x363 * 363x4608 + BETA * 96x4608) ====
GPU: 0.027932 [s], 1.15454e+10 [flop/s]
CPU (4 threads): 6.72671 [s], 4.79411e+07 [flop/s]
Minimum absolute error: 0
Maximum absolute error: 1089
Minimum relative error: 0
Maximum relative error: 0.749484, out1=364, out2=1453

**Comment by notogawa** [comment]
Thank you for your reporting. Try v0.0.1 release tag.

This behavior caused by VideoCoreIV hardware limit of DMA. In v0.0.0 SGEMM, only R < 2048 case is guaranteed. In reality, the practical upper limit may be larger than documented (at The VideoCoreIV reference manual) one. However, we can't know the correct upper limit and we didn't need this case in the short-term future.

In v0.0.1, we relax this limitation. Even if R >= 2048, SGEMM works well. This implementation is just software workaround, so SGEMM for R >= 2048 has slightly worse performance than R < 2048 one.

**Comment by sasao-balmuda** [comment]
Thanks for your quick solution.  I tried some combinations of P,Q,R and no problems I met.
